FROM php:7.2-apache

# Install extensions
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
        sqlite3 \
    && docker-php-ext-install -j$(nproc) iconv \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd

# Prepare files and folders
RUN mkdir -p /speedtest/

# Copy sources
COPY backend/ /speedtest/backend
COPY results/*.php /speedtest/results/
COPY results/*.ttf /speedtest/results/
COPY *.js /speedtest/
#COPY docker/servers.json /servers.json
COPY docker/*.php /speedtest/
COPY docker/entrypoint.sh /

# Prepare environment variabiles defaults
ENV TITLE=$(TITLE)
ENV MODE=$(MODE)
ENV PASSWORD=$(PASSWORD)
ENV TELEMETRY=$(TELEMETRY)
ENV ENABLE_ID_OBFUSCATION=$(ENABLE_ID_OBFUSCATION)
ENV REDACT_IP_ADDRESSES=$(REDACT_IP_ADDRESSES)

# Final touches
EXPOSE 80
CMD ["bash", "/entrypoint.sh"]
