version: "3.3"
networks:
    lognet:
      external: true

services:
  fluentd:
    build: ./fluentd
    restart: unless-stopped
    environment:
      - elasticsearch_hosh=elasticsearch
      - elasticsearch_port=9200
    ports:
      - 24224:24224
      - 24224:24224/udp
    networks:
      lognet:
 #      aliases:
 #       - fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    logging:
      driver: json-file
# Using the same default setting
      options:
        max-size: 10m
        max-file: "5"
        labels: "fluentd_log"

  elasticsearch:
    image: elasticsearch:7.5.2
    restart: unless-stopped
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - http.host=0.0.0.0
      - http.max_content_length=200m
      - transport.host=127.0.0.1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    expose:
      - 9200
    ports:
      - 9200:9200
    networks:
      lognet:
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: elasticsearch_log

  kibana:
    image: kibana:7.5.2
    restart: unless-stopped
    environment:
      - server.name=kibana
      - elasticsearch.hosts=elasticsearch
      - server.maxPayloadBytes=524288
    ports:
      - 5601:5601
    networks:
      lognet:
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: kibana_log
